# https://eslint.org/docs/user-guide/configuring/rules#configuring-rules

env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard
  - eslint-config-prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {}

# Add Vitest
overrides:
  [
    {
      files: ['*.spec.tsx', '*.test.tsx'],
      rules: { no-undef: off, no-unused-vars: off },
    },
  ]
